
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles
  gateway:
    build: ./foodgram_proxy/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend