[tool.ruff]
line-length = 80
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "Q", "I", "B", "C4", "UP"]  # Q — это flake8-quotes

per-file-ignores = {"backend/settings.py" = ["ALL"], "*/migrations/*" = ["ALL"]}

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"

[tool.ruff.isort]
known-first-party = ["backend", "recipes", "api"]
known-third-party = [
    "django",
    "rest_framework", 
    "djoser",
    "reportlab",
    "PIL",
    "requests",
]
lines-between-types = 1
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.format]
indent-style = "space"