# Generated by Django 4.2 on 2025-09-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Tags",
        ),
        migrations.RenameField(
            model_name="recipes",
            old_name="tag",
            new_name="tags",
        ),
    ]
