# Generated by Django 4.2 on 2025-09-23 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_rename_tag_tags_rename_tag_recipes_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipes",
            old_name="coocking_time",
            new_name="cooking_time",
        ),
    ]
