# Generated by Django 4.2 on 2025-09-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_rename_coocking_time_recipes_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientsinrecipes",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_recipes",
                to="recipes.ingredients",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsinrecipes",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="recipes.recipes",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.IngredientsInRecipes",
                to="recipes.ingredients",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientsinrecipes",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
    ]
