# Generated by Django 4.2 on 2025-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_ingredientsinrecipes_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="short_link",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Короткая ссылка",
            ),
        ),
    ]
