# Generated by Django 4.2 on 2025-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipes_short_link_shopingcart_favorites_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopingCart",
            new_name="ShoppingCart",
        ),
    ]
