# Generated by Django 4.2 on 2025-10-03 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_rename_shopingcart_shoppingcart"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="fooduser",
            managers=[],
        ),
    ]
