# Generated by Django 4.2 on 2025-10-05 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_fooduser_managers"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_follow",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="prevent_self_follow",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="following",
        ),
        migrations.AddField(
            model_name="subscription",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="unique_subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("author")), _negated=True),
                name="prevent_self_follow",
            ),
        ),
    ]
