# Generated by Django 4.2 on 2025-10-06 17:30

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_remove_subscription_unique_follow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooduser",
            name="avatar",
            field=models.ImageField(upload_to=recipes.models.user_avatar_path),
        ),
    ]
