# Generated by Django 4.2 on 2025-10-09 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_alter_fooduser_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipes",
            old_name="description",
            new_name="text",
        ),
    ]
