# Generated by Django 5.2.7 on 2025-10-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_alter_favorites_options_alter_recipes_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipes",
            options={
                "ordering": ("pub_date",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
