# Generated by Django 5.2.7 on 2025-10-12 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0015_alter_recipes_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipes",
            options={
                "default_related_name": "recipes",
                "ordering": ("-pub_date",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterField(
            model_name="recipes",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="tags",
            field=models.ManyToManyField(
                to="recipes.tags", verbose_name="Теги"
            ),
        ),
    ]
