# Generated by Django 4.2 on 2025-10-20 19:01

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0016_alter_recipes_options_alter_recipes_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredients",
            options={
                "ordering": ("-name",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredientsinrecipes",
            options={
                "default_related_name": "recipe_ingredients",
                "verbose_name": "Продукт в рецепте",
                "verbose_name_plural": "Продукты в рецептах",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "default_related_name": "shopping_carts",
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
        migrations.AlterModelManagers(
            name="fooduser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="shoppingcart",
            name="unique_shopping_cart",
        ),
        migrations.RemoveField(
            model_name="recipes",
            name="short_link",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="user",
        ),
        migrations.AlterField(
            model_name="ingredientsinrecipes",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsinrecipes",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.ingredients"
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsinrecipes",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.recipes"
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="cooking_time",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Время приготовления (мин)",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Авторы",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчики",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredients",
            constraint=models.UniqueConstraint(
                fields=("name", "measurement_unit"), name="unique_ingredient"
            ),
        ),
    ]
