# Generated by Django 4.2 on 2025-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_alter_ingredients_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="slug",
            field=models.SlugField(max_length=32, unique=True, verbose_name="Слаг"),
        ),
    ]
