# Generated by Django 4.2 on 2025-10-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0019_shoppingcart_recipe_shoppingcart_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorites",
            name="unique_favorite",
        ),
        migrations.AlterField(
            model_name="recipes",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.IngredientsInRecipes",
                to="recipes.ingredients",
                verbose_name="Продукты",
            ),
        ),
    ]
