# Generated by Django 5.2.7 on 2025-10-24 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_remove_favorites_unique_favorite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="cooking_time",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Время (мин)",
            ),
        ),
    ]
