# Generated by Django 4.2 on 2025-10-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0023_alter_favorites_options_alter_shoppingcart_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientsinrecipes",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.ingredients",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientsinrecipes",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipes",
                verbose_name="Рецепт",
            ),
        ),
    ]
